### PR TITLE
Fixed Typo in README

### PR DESCRIPTION
**Pull request by devium335**
Made `sercet` into `secret` in the `README.md` in reference to the env file

### CODE REVIEW

**Comment by ChocoMeow** [comment]
Thank you for correcting my typo. <3

**Comment by devium335** [comment]
One thing I haven't checked yet is if it's referenced as it was with the typo in the code

**Comment by ChocoMeow** [comment]
Yes, I know—I’ll try to fix everything at once

**Comment by devium335** [comment]
> Yes, I know—I’ll try to fix everything at once

Fixed them in above commit

**Pull request merged**
